# Generated by Django 4.2.4 on 2023-08-29 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperDetailInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper_language",
                    models.CharField(
                        blank=True, default="English", max_length=20, null=True
                    ),
                ),
                (
                    "paper_volume",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("paper_issue", models.CharField(blank=True, max_length=10, null=True)),
                ("paper_page", models.CharField(blank=True, max_length=255, null=True)),
                ("paper_doi", models.CharField(blank=True, max_length=255, null=True)),
                ("paper_ids", models.CharField(blank=True, max_length=255, null=True)),
                ("paper_wos", models.CharField(blank=True, max_length=255, null=True)),
                ("data_status", models.BooleanField(default=True)),
                ("edit_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "db_paper_detail_info",
            },
        ),
        migrations.CreateModel(
            name="SourceDetailInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255, unique=True)),
                ("source_type", models.CharField(default="J", max_length=2)),
                ("source_date", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_publisher",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_issn",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_eissn",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_isbn",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_abbreviation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_status", models.BooleanField(default=True)),
                ("edit_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "db_source_detail_info",
            },
        ),
        migrations.CreateModel(
            name="PaperMainInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paper_title", models.CharField(max_length=255)),
                ("paper_author", models.CharField(max_length=255)),
                ("paper_public_year", models.IntegerField(blank=True, null=True)),
                (
                    "paper_keywords",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paper_abstract", models.TextField(blank=True, null=True)),
                (
                    "paper_affiliations",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_status", models.BooleanField(default=True)),
                ("edit_date", models.DateTimeField(auto_now_add=True)),
                (
                    "paper_source",
                    models.ForeignKey(
                        db_column="source_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paper.sourcedetailinfomodel",
                    ),
                ),
            ],
            options={
                "db_table": "db_paper_main_info",
            },
        ),
        migrations.CreateModel(
            name="PaperFilePathModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FileField(null=True, upload_to="static/papers")),
                ("data_status", models.BooleanField(default=True)),
                ("edit_date", models.DateTimeField(auto_now_add=True)),
                (
                    "paper_id",
                    models.ForeignKey(
                        db_column="paper_detail_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paper.paperdetailinfomodel",
                    ),
                ),
            ],
            options={
                "db_table": "db_paper_file_path",
            },
        ),
        migrations.CreateModel(
            name="PaperDownloadCountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("download_count", models.IntegerField(default=0)),
                ("data_status", models.BooleanField(default=True)),
                ("edit_date", models.DateTimeField(auto_now_add=True)),
                (
                    "paper_id",
                    models.OneToOneField(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paper.papermaininfomodel",
                    ),
                ),
            ],
            options={
                "db_table": "db_paper_download_count",
            },
        ),
        migrations.AddField(
            model_name="paperdetailinfomodel",
            name="paper_id",
            field=models.OneToOneField(
                db_column="paper_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="paper.papermaininfomodel",
            ),
        ),
        migrations.CreateModel(
            name="PaperCitedCountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cited_reference_count", models.IntegerField(default=0)),
                ("cited_times", models.IntegerField(default=0)),
                ("data_status", models.BooleanField(default=True)),
                ("edit_date", models.DateTimeField(auto_now_add=True)),
                (
                    "paper_id",
                    models.OneToOneField(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paper.papermaininfomodel",
                    ),
                ),
            ],
            options={
                "db_table": "db_paper_cited_count",
            },
        ),
    ]
