# Generated by Django 4.2.4 on 2023-08-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paper", "0002_alter_papermaininfomodel_paper_affiliations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedetailinfomodel",
            name="source_publisher",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
