# Generated by Django 4.2.4 on 2023-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "paper",
            "0005_rename_paper_public_year_papermaininfomodel_paper_publish_year",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentAndSuggestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="ICost", max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("comment", models.TextField(max_length=1024)),
                ("unsolved", models.BooleanField(default=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("edit_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
